Redux+Saga
deman4ela/marvel pull request #6
Opened 2021-10-21 09:25 UTC by deman4ela

2021-10-22 16:06 UTC, alinalaktionova requested changes

2021-10-22 16:06 UTC, alinalaktionova commented on src/Alert.tsx
> +       Unfortunately, {`${props.fetchedHeroesError}`} error occurred. Please try again later.
the message is the same, you can simplify and create one if statement

2021-10-22 16:06 UTC, alinalaktionova commented on src/redux/connects/connectHeroes.tsx
> +const mapDispatchToProps = (dispatch: any) => ({
remove any

2021-10-22 16:06 UTC, alinalaktionova commented on src/Components/ComicsOfHero.tsx
> +    (() => this.props.fetchComics(this.props.match.params.heroID))();
why do you use anonymous func for this?

2021-10-22 16:06 UTC, alinalaktionova commented on src/Components/Heroes.tsx
> +    if (searchedHeroName === undefined) {
JUST searchedHeroName

2021-10-22 16:06 UTC, alinalaktionova commented on src/Components/Heroes.tsx
> +    (() => this.props.fetchHeroes(searchedHeroName))();
again anonymous func

2021-10-22 16:06 UTC, alinalaktionova commented on src/api/api.tsx
> +  if (searchedHeroName === '') {
no need to compare with empty string

2021-10-22 16:06 UTC, alinalaktionova commented on src/redux/actions.tsx
> +export const fetchHeroesSuccess = (heroes: any) => ({ type: FETCH_HEROES_SUCCESS, payload: heroes });
remove any

2021-10-22 16:06 UTC, alinalaktionova commented on src/redux/actions.tsx
> +export const showLoaderHeroes = () => ({ type: SHOW_LOADER_HEROES });
you can show loader in fetchHeroes action, it's not necessary to create separate action for this

2021-10-22 16:06 UTC, alinalaktionova commented on src/redux/types.tsx
> +export const FETCH_HEROES = 'HERO/FETCH_HEROES';
why HERO/ ?

2021-10-22 16:06 UTC, alinalaktionova commented on src/redux/types.tsx
> +export const FETCH_HEROES = 'HERO/FETCH_HEROES';
just FETCH_HEROES

2021-10-22 16:06 UTC, alinalaktionova commented on src/redux/types.tsx
> +export const FETCH_COMICS = 'COMIC/FETCH_COMICS';
the same

2021-10-22 16:06 UTC, alinalaktionova commented on src/Components/Heroes.tsx
> +    const { fetchedHeroesSuccess, fetchedHeroesError, loaderWorksHeroes } = this.props;
loaderWorksHeroes is bad naming, rename

2021-10-25 11:23 UTC, deman4ela commented on src/Components/ComicsOfHero.tsx
> +    (() => this.props.fetchComics(this.props.match.params.heroID))();
I used an example from some source and did not change it. 
Now, it is changed and anonymous function is removed.

2021-10-25 11:25 UTC, deman4ela commented on src/Components/Heroes.tsx
> +    (() => this.props.fetchHeroes(searchedHeroName))();
Changed

2021-10-25 11:29 UTC, deman4ela commented on src/Components/Heroes.tsx
> +    if (searchedHeroName === undefined) {
Changed to:
if (!searchedHeroName)

2021-10-25 11:39 UTC, deman4ela commented on src/Components/Heroes.tsx
> +    const { fetchedHeroesSuccess, fetchedHeroesError, loaderWorksHeroes } = this.props;
Renamed to 'loaderForHeroes'

2021-10-25 11:44 UTC, deman4ela commented on src/api/api.tsx
> +  if (searchedHeroName === '') {
Fixed.

2021-10-27 14:56 UTC, alinalaktionova requested changes

2021-10-27 14:56 UTC, alinalaktionova commented on src/redux/actions.tsx
>  export const hideLoaderHeroes = () => ({ type: HIDE_LOADER_HEROES });
you can hide loader in success or error action and not to create separate one for this logic

2021-11-01 14:49 UTC, alinalaktionova approved these changes

2021-11-01 18:27 UTC, merged